### ISSUE TITLE
Program crash.

### ISSUE THREAD

**Issue by aking6083** [aking6083/kingTranAssn3#8] opened 2015-01-31 15:12 UTC
Why is it crashing here??  We need to have a functional methods before merging to main(), 
![image](https://cloud.githubusercontent.com/assets/3180395/5988517/86f85f60-a931-11e4-89ba-51f0030e8e96.png)

**Comment by ctran88** [comment] 2015-01-31 15:29
What do you mean crashing?  I tested it multiple times without a crash before posting changes and merging

**Comment by ctran88** [comment] 2015-01-31 15:37
Ah.  Sorry, it's my bad.  When I was testing, it was with low value constants for list size and table size.  I just have to adjust doubleHash() because it keeps trying to read openTable[newAddy] with an address that is out of range.  I will fix it right away.

**Comment by aking6083** [comment] 2015-01-31 15:39
Don't mess with main I'm working my chainz

**Comment by ctran88** [comment] 2015-01-31 15:39
i'm doing it on TranTesting

**Comment by aking6083** [comment] 2015-01-31 15:41
cool, I'll merge it to master..  Let me know..

AK

**Comment by ctran88** [comment] 2015-01-31 15:41
It'll be fixed in the next few minutes

**Comment by ctran88** [comment] 2015-01-31 17:32
alright wasn't as easy as I thought...For some reason I keep running into an infinite loop here with doubleHash()...Here's my code:

int doubleHash(int theNum, int tableSize, int openTable[], int &count)
{
    int primHash,
        secHash,
        newAddy;

```
count = 1;
primHash = getHash(theNum, tableSize);

// if primary hash does not result in collision
if (openTable[primHash] == 0)
{
    newAddy = primHash;
    return newAddy;
}
else
{
    secHash = (theNum % (tableSize - 2)) + 1;
    newAddy = (primHash + secHash) % tableSize;

    // loops while double-hashed address is not empty
    while ((openTable[newAddy] != 0))
    {
        newAddy = (newAddy + secHash) % tableSize;
        count++;
    }   
}

return newAddy;
```

You think you might be able to help me figure out what the problem is?

**Comment by aking6083** [comment] 2015-01-31 17:39
looks like somewhere in the comparison.
Check to make sure all keys in the openTable or actually set to zero.
I had to do that with my chain function, it kept crashing on that
comparison, because it is comparing to garbage memory locations.
So I would make sure all ints in the array actually set to zero at init.

AK

**Comment by ctran88** [comment] 2015-01-31 17:45
Yeah everything in openTable is set to zero.  What happens is that sometimes it'll keep doing an infinite loop because the iterations of addresses it searches for are all taken.  However, it can only search certain addresses because of the way double hashing works.  So it will never find the empty addresses.  I triple-checked the formula; it should be right.  Don't know what's going on.

**Comment by ctran88** [comment] 2015-01-31 17:48
I think it happens when the table size isn't a prime number..

**Comment by ctran88** [comment] 2015-01-31 17:49
well, it depends on what random numbers generate..but it happens more often when it isn't a prime number.

**Comment by aking6083** [comment] 2015-01-31 17:52
maybe not, let me finish my functions and I'll see what I can see.

AK

**Comment by aking6083** [comment] 2015-01-31 17:55
the table size has to be much greater than the random number size as well I
read in the content.

AK

**Comment by ctran88** [comment] 2015-01-31 17:57
well, with the highest test load factor of 0.75, I tested it. i.e. list size of 5000 and table size of 6700 is about 0.746 load factor.  still came up with an infinite loop.

**Comment by ctran88** [comment] 2015-01-31 17:57
and i'm pretty sure the infinite loops are only caused by the double hashing not searching every index in the table.

**Closed as completed** 2015-01-31 22:20 UTC
